fix(#32): now public access modifier is added on ts transformation level
alexeychikk/ts2hx pull request #41
Opened 2023-10-03 14:21 UTC by VintorezVS

2023-10-03 16:40 UTC, alexeychikk requested changes

2023-10-03 16:40 UTC, alexeychikk commented on tests/classes/transformClassDeclaration.test.ts
> +  class Foo {
Please get rid of additional tabulation, check other tests. Make sure enclosing "`" is also at the start of the line.

2023-10-03 16:40 UTC, alexeychikk commented on src/transformers/Transpiler.ts
> +  node: ts.Node & { parent: ts.Node['parent'] | undefined },
I don't think this is necessary. Compiles even without this change.
For example, `ts.SourceFile` doesn't have parent and still ts devs didn't make it optional.

2023-10-03 16:40 UTC, alexeychikk commented on src/transformers/ts/objects.ts
> +  if (!ts.isObjectLiteralExpression(this.utils.getParentNode(node))) return;
I'm curious why have you replaced `node.parent` only here and not everywhere else?

2023-10-03 16:40 UTC, alexeychikk commented on src/transformers/utils/common.ts
> +  return node.parent ?? ts.getOriginalNode(node).parent;
I think I understand why this is needed but I don't like this solution.
I guess I know where we got things wrong: we are using just 1 transformer here:
https://github.com/alexeychikk/ts2hx/blob/965f5f8fab46799b33654eda598e1941c3502399/src/transformers/Transpiler.ts#L61
I think what we should've done is to map our transformers to a set of `ts.TransformerFactory`.
Maybe this way ts would do parents linking for us.

2023-10-03 16:43 UTC, alexeychikk requested changes

2023-10-03 16:43 UTC, alexeychikk commented on tests/classes/transformClassDeclaration.test.ts
> +test('adds access modifier for class members', async () => {
1 test file is intended for 1 particular transformer. Please extract this test into a separate file

2023-10-03 17:27 UTC, VintorezVS commented on src/transformers/Transpiler.ts
> +  node: ts.Node & { parent: ts.Node['parent'] | undefined },
ups forgot to remove this

2023-10-03 17:28 UTC, VintorezVS commented on src/transformers/ts/objects.ts
> +  if (!ts.isObjectLiteralExpression(this.utils.getParentNode(node))) return;
It is needed only for ts transformation layer.

2023-10-04 16:24 UTC, alexeychikk approved these changes

2023-10-04 16:24 UTC, merged